### PR TITLE
Fix upgrade regexp

### LINKED ISSUE #14: Wrong upgrade regexp
We are in cyber~Congress researching upgrades functionality and found that cosmosd doesn't automatically migrate to new binary when needed

For example, the node produces this output when triggered upgrade (proposal with empty plan info):
```
UPGRADE "euler-8" NEEDED at height: 16000:
```

And cosmosd doesn't upgrade and relink to new binary because scanner doesn't match upgrade string with current regexp:
```
UPGRADE "(.*)" NEEDED at height (\d+):\s+([^\s]*)
```
But with following regexp all things done:
```
UPGRADE "(.*)" NEEDED at height: (\d+):\s+([^\s]*)
```

__plan.DueAt() returns height: block_number__
https://github.com/cosmos/cosmos-sdk/blob/release/v0.38.2/x/upgrade/abci.go#L38
https://github.com/cosmos/cosmos-sdk/blob/release/v0.38.2/x/upgrade/internal/types/plan.go#L77

Note: cosmos-sdk 0.38.{1,2}

@ethanfrey @aaronc

### PR DESCRIPTION
**Pull request by ethanfrey**
Closes #14 

This updates the scanner to use both possible info lines printed from cosmos-sdk v0.38

Thanks to @litvintech for discovered and reporting this.

### CODE REVIEW

**Review by aaronc — APPROVED** [review]
LGTM

**Comment by aaronc** [comment]
@anilCSE if this looks good to you I'll go ahead and merge.

**Comment by aaronc** [comment]
Thanks @ethanfrey !

**Comment by cyborgshead** [comment]
Thanks for fast delivery!

**Review by anilcse — APPROVED** [review]
ACK :tada:

**Comment by ethanfrey** [comment]
I merged with the acks.
I would tag a v0.3.0 release as this is incompatible with v0.2.0. Or should we use v0.2.1 as a bugfix?

I think @litvintech wants a tagged release soon, and it would also be nice for the Regen validators, but I think less urgent there.

**Comment by cyborgshead** [comment]
Thanks @ethanfrey  for the fast resolution of this issue. New release tag will be awesome but anyway we have in our node's guide workflow to build cosmosd from sources from the master branch

**Pull request merged**
